name: "Build workflow"
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update OS
      run: |
        uname -a
        sudo yum install -y -q gcc mingw64-SDL2-static mingw64-gcc-c++ ninja
    - name: Build Linux package
      run: |
        mkdir -p build-linux && cd build-linux && cmake .. -GNinja && ninja
      shell: bash
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: TressFX-linux
        path: build-linux/package/*
              LICENSE
    - name: Build Linux package
      run: |
        mkdir -p build-windows && cd build-windows && cmake .. -GNinja && ninja
      shell: bash
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: TressFX-windows
        path: build-windows/package/*
              LICENSE
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: true
        title: TressFX packages
        files: |
          TressFX-linux.zip
          TressFX-windows.zip