name: "Build workflow"
on: [push]
jobs:
  build-windows:
    runs-on: ubuntu-latest
    container:
      image: fedora:34
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update OS
      run: |
        uname -a
        yum install -y mingw64-gcc-c++ python ninja-build glibc-devel cmake mingw64-SDL2 mingw64-SDL2-static pkg-config
    - name: Build Windows package
      run: |
        mkdir -p build-windows
        python3 bin/build_glsl.py
        cd build-windows
        cmake -DCMAKE_TOOLCHAIN_FILE=../Toolchain-fedora-mingw64.cmake .. -GNinja
        ninja
      shell: bash
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: TressFX-windows
        path: build-windows/package/*
              LICENSE
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-windows
        prerelease: true
        title: TressFX packages
        files: |
          TressFX-windows.zip
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update OS
      run: |
        uname -a
        yum install -y epel-release
        dnf install -y dnf-plugins-core
        dnf config-manager --set-enabled powertools
        yum install -y python clang SDL2-devel ninja-build cmake pkg-config
    - name: Build Linux package
      run: |
        mkdir -p build-linux
        python3 bin/build_glsl.py
        cd build-linux
        cmake .. -GNinja
        ninja
      shell: bash
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: TressFX-linux
        path: build-linux/package/*
              LICENSE
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-linux
        prerelease: true
        title: TressFX packages
        files: |
          TressFX-linux.zip